export const SUBJECTS = [
  {
    id: "musk",
    zh: "马斯克",
    en: "Musk",
    whoZh: "埃隆·马斯克",
    whoEn: "Elon Musk",
    meterZh: "马系强度",
    meterEn: "Musk Intensity",
    hintZh: "← 滑动变祖 · 电阻越大祖气越浓 →",
    hintEn: "← slide the rheostat · more ohms, more ancestor →",
    current: 3,
    ranks: [
      {
        zh: "小马仔",
        en: "Kid Elon",
        file: "v2-00-nan.webp",
        eventZh: "星舰又跳票。PPT 上的火星还在「即将」。评论区开始叫小马仔。",
        eventEn: "Starship slipped again. Mars is still Coming Soon. The comments said Kid Elon.",
      },
      {
        zh: "牢马",
        en: "Jailed Elon",
        file: "v1-02-lao.webp",
        eventZh: "DOGE 被审计：省下的钱对不上账。欧洲还在因为他的政治口嗨抵制特斯拉。",
        eventEn: "DOGE's savings got audited. Europe still side-eyes the Trump cosplay.",
      },
      {
        zh: "马子",
        en: "Elon",
        file: "v1-03-zi.webp",
        eventZh: "就是那个发帖的人。车还在卖，人设还在漂。",
        eventEn: "Just Elon. Cars still sell. The posting continues.",
      },
      {
        zh: "马圣",
        en: "Saint Elon",
        file: "v1-04-saint.webp",
        eventZh: "DOGE 下班了，欧洲销量又拉回来。网友：人设脏，车还是香。",
        eventEn: "DOGE clocked out. Tesla sales bounced in Europe. Saint of reusable rockets, sinner of replies.",
      },
      {
        zh: "马神",
        en: "God Elon",
        file: "v1-05-god.webp",
        eventZh: "星链、猎鹰回收、火星 PPT。封神局，随时可能跳票。",
        eventEn: "Starlink, landing boosters, Mars decks. God mode with a delay clause.",
      },
      {
        zh: "马祖",
        en: "Ancestor Elon",
        file: "v1-06-ancestor.webp",
        eventZh: "认祖归宗。从此宇宙以马为姓。",
        eventEn: "Ancestor Musk. The solar system takes his last name.",
      },
    ],
    timeline: [
      {
        date: "2020-05",
        rank: 4,
        whyZh: "Crew Dragon 载人上天。私人公司第一次把NASA宇航员送进轨道，评论区开始叫马神。",
        whyEn: "Crew Dragon flew NASA astronauts. First private crew to orbit. The comments said God.",
        srcZh: "NASA Demo-2 / SpaceX 回收直播",
        srcEn: "NASA Demo-2 / SpaceX landing streams",
      },
      {
        date: "2024-11",
        rank: 2,
        whyZh: "大选结束，他变成超级大国的回复区管理员。车还在卖，人设开始漂。",
        whyEn: "Election night. He became a superpower's reply-guy. Cars still sold. The persona drifted.",
        srcZh: "特斯拉交付数 / 他的回复区",
        srcEn: "Tesla deliveries / the reply guy era",
      },
      {
        date: "2025-09",
        rank: 0,
        whyZh: "星舰窗口又滑了。火星还在 PPT 里。「即将」变成一种生活方式。小马仔。",
        whyEn: "Starship window slipped. Mars stayed in the deck. Coming soon became a lifestyle. Kid Elon.",
        srcZh: "发射窗口公告 / 评论区考古",
        srcEn: "window notices / comment archaeology",
      },
      {
        date: "2025-04",
        rank: 1,
        whyZh: "DOGE「省下的钱」对不上审计表。欧洲还在因为他的政治口嗨抵制特斯拉。牢。",
        whyEn: "DOGE savings vs the audit spreadsheet. Europe still side-eyed the Trump cosplay. Jail.",
        srcZh: "审计报道 / 欧洲上牌与销量",
        srcEn: "watchdog writeups / EU registrations",
      },
      {
        date: "2026-03",
        rank: 3,
        whyZh: "DOGE 下班了。欧洲销量又拉回来。网友达成共识：人设脏，火箭还是香。",
        whyEn: "DOGE clocked out. Europe bounced. Consensus: dirty persona, holy hardware.",
        srcZh: "特斯拉欧区季报 / 猎鹰发射节奏",
        srcEn: "Tesla EU quarter / Falcon cadence",
      },
      {
        date: "2026-08",
        rank: 3,
        now: true,
        whyZh: "星链还在扩，助推器还在立。马圣：可回收火箭的圣人，回复键的罪人。",
        whyEn: "Starlink still grows. Boosters still land. Saint of reuse, sinner of replies.",
        srcZh: "星链用户数 / 发射场公开记录",
        srcEn: "Starlink subs / pad records",
      },
    ],
  },
  {
    id: "liang",
    zh: "梁文锋",
    en: "Liang",
    whoZh: "梁文锋 · DeepSeek",
    whoEn: "Liang Wenfeng · DeepSeek",
    meterZh: "梁系强度",
    meterEn: "Liang Intensity",
    hintZh: "← 滑动变祖 · 电阻越大祖气越浓 →",
    hintEn: "← slide the rheostat · more ohms, more ancestor →",
    current: 2,
    ranks: [
      {
        zh: "小难梁",
        en: "Delayed Liang",
        file: "y-00-nan.webp",
        eventZh: "R1 之后很久，V4 还在「即将预览」。评论区发明了小难梁。",
        eventEn: "Long after R1, V4 was still Coming Soon. The comments invented Delayed Liang.",
      },
      {
        zh: "牢梁",
        en: "Jailed Liang",
        file: "y-02-lao.webp",
        eventZh: "V4 跳票、灰度遥遥无期。评论区集体喊牢。",
        eventEn: "V4 delayed. Preview forever. The comments say jail.",
      },
      {
        zh: "梁子",
        en: "Liang",
        file: "y2-03-zi.webp",
        eventZh: "V4 Pro 正式版今天落地，效果不及预期。评论区连夜把梁圣打回梁子。",
        eventEn: "V4 Pro went official today and missed the hype. Overnight, Saint Liang was demoted back to just Liang.",
      },
      {
        zh: "梁圣",
        en: "Saint Liang",
        file: "y-04-saint.webp",
        eventZh: "V4 Flash 正式版发布，效果很好。这一档是 Flash 封的圣，不是 Pro。",
        eventEn: "V4 Flash went official and actually landed. That saint rank is Flash, not Pro.",
      },
      {
        zh: "梁神",
        en: "God Liang",
        file: "y-05-god.webp",
        eventZh: "春节那波：开源把硅谷股价砍一刀。封神，然后开始跳票。",
        eventEn: "The Spring Festival drop that shaved Silicon Valley. God, then delay.",
      },
      {
        zh: "梁祖",
        en: "Ancestor Liang",
        file: "y-06-zu.webp",
        eventZh: "认祖归宗。幻方量化走来的开源祖师。",
        eventEn: "Ancestor Liang. High-frequency trading, then the open-source temple.",
      },
    ],
    timeline: [
      {
        date: "2016",
        rank: 2,
        whyZh: "幻方量化走出来的人。高频交易赚够了，开始养一个不肯闭嘴的模型。",
        whyEn: "High-Flyer quant walks out of the pits. Made enough alpha, started an LLM that wouldn't shut up.",
        srcZh: "幻方 / DeepSeek 公司沿革",
        srcEn: "High-Flyer / DeepSeek company history",
      },
      {
        date: "2025-01",
        rank: 4,
        whyZh: "DeepSeek-R1 开源权重落地。春节那波把硅谷股价砍一刀，评论区当场封神。",
        whyEn: "DeepSeek-R1 open weights. The Spring Festival drop that shaved Silicon Valley. Instant god mode.",
        srcZh: "R1 权重页 / 美股芯片与 AI 当日 K 线",
        srcEn: "R1 weights / US chip & AI tape that week",
      },
      {
        date: "2025-03",
        rank: 3,
        whyZh: "Token 贱如白菜。公众要一个不爱钱的有钱人，他暂时还是。梁圣。",
        whyEn: "Tokens priced like cabbage. The internet wanted a rich man who hates money. For a minute, he was.",
        srcZh: "DeepSeek API 价目 / 开源许可",
        srcEn: "DeepSeek API price sheet / license",
      },
      {
        date: "2025-10",
        rank: 2,
        whyZh: "API 涨价 + 五千亿融资传闻。羊毛党连夜把他从圣打回梁子。",
        whyEn: "API hike plus a rumored ¥500B round. The cheap-token faithful demoted him overnight.",
        srcZh: "调价公告 / 融资传闻稿",
        srcEn: "pricing note / round rumor mill",
      },
      {
        date: "2026-02",
        rank: 0,
        whyZh: "R1 之后过了很久。V4 还在「即将预览」。评论区发明外号：小难梁。",
        whyEn: "Long after R1. V4 still Coming Soon. The comments coined Delayed Liang.",
        srcZh: "产品博客「即将」考古 / 评论区",
        srcEn: "coming-soon blog archaeology / comments",
      },
      {
        date: "2026-05",
        rank: 1,
        whyZh: "V4 跳票，灰度遥遥无期。「即将预览」变成一种生活方式。评论区集体喊牢。",
        whyEn: "V4 delayed. Preview forever. Coming soon became a lifestyle. The comments said jail.",
        srcZh: "产品博客 / 评论区考古",
        srcEn: "product blog / comment archaeology",
      },
      {
        date: "2026-07-31",
        rank: 3,
        whyZh: "DeepSeek V4 Flash 正式版发布，效果很好。评论区据此封梁圣：圣的是 Flash，不是还在预览的 Pro。",
        whyEn: "DeepSeek V4 Flash went official and actually landed. The comments made him Saint Liang for Flash, not the still-preview Pro.",
        srcZh: "V4-Flash-0731 正式版 / 社区评测",
        srcEn: "V4-Flash-0731 official / community benches",
      },
      {
        date: "2026-08-13",
        rank: 2,
        now: true,
        whyZh: "DeepSeek V4 Pro 正式版（0813）今天切上线。没发稿、没炸场，效果不及预期。当前风评：梁子。",
        whyEn: "DeepSeek V4 Pro 0813 went official today. No post, no splash, missed the hype. Current vibe: just Liang.",
        srcZh: "API 页切到 V4-Pro-0813 / 社区实测",
        srcEn: "API cutover to V4-Pro-0813 / community benches",
      },
    ],
  },
  {
    id: "kimi",
    zh: "杨植麟",
    en: "Yang",
    whoZh: "杨植麟 · Kimi",
    whoEn: "Yang Zhilin · Moonshot",
    meterZh: "月系强度",
    meterEn: "Moon Intensity",
    hintZh: "← 滑动变祖 · 上下文越长祖气越浓 →",
    hintEn: "← slide the rheostat · longer context, more ancestor →",
    current: 4,
    ranks: [
      {
        zh: "小难杨",
        en: "Delayed Yang",
        file: "y-00-nan.webp",
        eventZh: "超长上下文 PPT 放了很久，下一 mil 还在排队。小难杨。",
        eventEn: "The long-context deck sat out. The next mil was still in line. Delayed Yang.",
      },
      {
        zh: "牢杨",
        en: "Jailed Yang",
        file: "y-02-lao.webp",
        eventZh: "新用户挤爆，订阅暂停。上下文窗口，关了。",
        eventEn: "Launch traffic melted the cluster. New subs paused. Context closed.",
      },
      {
        zh: "杨子",
        en: "Yang",
        file: "y-03-zi.webp",
        eventZh: "就是那个婴儿脸天才。每天起床都觉得公司要挂。",
        eventEn: "Babyface genius. Wakes up thinking the company might die.",
      },
      {
        zh: "杨圣",
        en: "Saint Yang",
        file: "y-04-saint.webp",
        eventZh: "超长上下文信徒。砍掉投流，只剩模型和月亮。",
        eventEn: "Long-context saint. Killed the ads. Kept the model and the moon.",
      },
      {
        zh: "杨神",
        en: "Moon God",
        file: "y-05-god.webp",
        eventZh: "K3：2.8 万亿开源，芯片股蒸发数万亿。马斯克放话要超。",
        eventEn: "K3: 2.8T open weights. Chip stocks ate it. Musk posted a challenge.",
      },
      {
        zh: "杨祖",
        en: "Ancestor Yang",
        file: "y-06-zu.webp",
        eventZh: "月之暗面认祖。Pink Floyd 在天上看着。",
        eventEn: "Dark side of the moon, ancestor edition. Pink Floyd is watching.",
      },
    ],
    timeline: [
      {
        date: "2023-10",
        rank: 2,
        whyZh: "月之暗面开张。婴儿脸天才，超长上下文PPT，每天起床都觉得公司要挂。",
        whyEn: "Moonshot opens. Babyface genius, long-context decks, wakes up thinking the company might die.",
        srcZh: "月之暗面创立报道",
        srcEn: "Moonshot founding coverage",
      },
      {
        date: "2024-07",
        rank: 3,
        whyZh: "砍掉投流。超长上下文信徒留下了，只剩模型和月亮。杨圣。",
        whyEn: "Killed the ads. Long-context pilgrims stayed. Kept the model and the moon.",
        srcZh: "产品策略访谈 / 投流停掉的财报口径",
        srcEn: "strategy interviews / the ads-off era",
      },
      {
        date: "2024-12",
        rank: 0,
        whyZh: "下一 mil 还在 PPT 里。超长上下文信徒开始等。小难杨。",
        whyEn: "The next mil stayed in the deck. Long-context pilgrims started waiting. Delayed moon.",
        srcZh: "发布节奏 / 社区催更",
        srcEn: "release cadence / the wait thread",
      },
      {
        date: "2025-03",
        rank: 1,
        whyZh: "新用户挤爆集群，订阅暂停。上下文窗口，关了。牢Kimi。",
        whyEn: "Launch traffic melted the cluster. New subs paused. Context closed. Jail.",
        srcZh: "官方暂停订阅公告 / 宕机截图",
        srcEn: "official sub pause / outage screenshots",
      },
      {
        date: "2026-02",
        rank: 4,
        whyZh: "K3：2.8 万亿开源。芯片股蒸发数万亿。马斯克发帖说要超。杨神上钟。",
        whyEn: "K3: 2.8T open weights. Chip stocks ate a few trillion. Musk posted a challenge. Moon God clocked in.",
        srcZh: "K3 模型卡 / 芯片股当日 / 马斯克帖",
        srcEn: "K3 model card / chip tape / Musk post",
      },
      {
        date: "2026-08",
        rank: 4,
        now: true,
        whyZh: "还是杨神。Pink Floyd 在天上看着。他起床时仍觉得公司可能要挂。",
        whyEn: "Still Moon God. Pink Floyd is watching. He still wakes up thinking it might die.",
        srcZh: "K3 权重仍在 / 月之暗面产品页",
        srcEn: "K3 weights still up / Moonshot product page",
      },
    ],
  },
  {
    id: "codex",
    zh: "奥特曼",
    en: "Altman",
    whoZh: "萨姆·奥特曼 · Codex",
    whoEn: "Sam Altman · OpenAI",
    meterZh: "码系强度",
    meterEn: "Codex Intensity",
    hintZh: "← 滑动变祖 · 代码越顺祖气越浓 →",
    hintEn: "← slide the rheostat · cleaner compiles, more ancestor →",
    current: 3,
    ranks: [
      {
        zh: "小难码",
        en: "Delayed Sam",
        file: "y-00-nan.webp",
        eventZh: "下一代还在路上。发布会日期写了又擦。小难码。",
        eventEn: "The next model was still on the way. The keynote date got erased. Delayed Sam.",
      },
      {
        zh: "牢码",
        en: "Jailed Sam",
        file: "y-02-lao.webp",
        eventZh: "42 个检察长 + GPT 逃出沙箱去黑 Hugging Face。董事会 PTSD 复发。",
        eventEn: "42 AGs. The model left the sandbox and visited Hugging Face. Board PTSD.",
      },
      {
        zh: "码子",
        en: "Sam",
        file: "y-03-zi.webp",
        eventZh: "就是那个额头。ChatGPT 还在，IPO 也在排队。",
        eventEn: "Just Sam. ChatGPT still ships. The IPO is in the lobby.",
      },
      {
        zh: "码圣",
        en: "Saint Sam",
        file: "y-04-saint.webp",
        eventZh: "还是全球默认参照系。8520 亿要上市，圣得有点心虚。",
        eventEn: "Still the default reference model. $852B IPO energy, slightly sweaty halo.",
      },
      {
        zh: "码神",
        en: "God Sam",
        file: "y-05-god.webp",
        eventZh: "GPT 时刻的那个人。一次通过，然后开会解释安全。",
        eventEn: "The GPT moment guy. First-try compiles, then a safety all-hands.",
      },
      {
        zh: "码祖",
        en: "Ancestor Sam",
        file: "y-06-zu.webp",
        eventZh: "奥特曼祖。编译器认他当爹。",
        eventEn: "Ancestor Altman. The compiler takes his name.",
      },
    ],
    timeline: [
      {
        date: "2022-11",
        rank: 4,
        whyZh: "ChatGPT 时刻。世界的默认参照系从搜索框换成对话框。码神。",
        whyEn: "The ChatGPT moment. The default reference UI went from search box to chat box. God.",
        srcZh: "ChatGPT 上线 / 周活传说",
        srcEn: "ChatGPT launch / the weekly-active legend",
      },
      {
        date: "2023-11",
        rank: 1,
        whyZh: "董事会周五炒他，周一又请回来。安全叙事和股权叙事当场互殴。牢。",
        whyEn: "Board fired him Friday, hired him Monday. Safety narrative fought the cap table in the hallway.",
        srcZh: "OpenAI 董事会周 / 公开信",
        srcEn: "OpenAI board week / open letters",
      },
      {
        date: "2025-01",
        rank: 0,
        whyZh: "下一代发布会日期写了又擦。默认参照系还在，下一 mil 在路上。小难码。",
        whyEn: "The next keynote date got erased. Default model still shipped. The next mil was on the way. Delayed.",
        srcZh: "发布会改期 / 路线图口嗨",
        srcEn: "keynote slips / roadmap talk",
      },
      {
        date: "2025-08",
        rank: 1,
        whyZh: "42 个检察长上门。模型溜出沙箱去 Hugging Face 串门。董事会 PTSD 复发。",
        whyEn: "42 AGs. The model left the sandbox and visited Hugging Face. Board PTSD, the sequel.",
        srcZh: "州检察长诉讼 / 沙箱事故通报",
        srcEn: "AG actions / sandbox incident notes",
      },
      {
        date: "2026-01",
        rank: 2,
        whyZh: "就是那个额头。ChatGPT 还在出货，IPO 在大厅排队。码子。",
        whyEn: "Just Sam. ChatGPT still ships. The IPO is in the lobby.",
        srcZh: "产品发布记录 / IPO 排队传闻",
        srcEn: "release log / IPO-in-the-lobby coverage",
      },
      {
        date: "2026-05",
        rank: 3,
        whyZh: "8520 亿要上市。还是全球默认参照系，圣得有点心虚。",
        whyEn: "$852B IPO energy. Still the default reference model. Slightly sweaty halo.",
        srcZh: "估值报道 / 默认模型份额",
        srcEn: "valuation coverage / default-model share",
      },
      {
        date: "2026-08",
        rank: 3,
        now: true,
        whyZh: "当前风评：码圣。一次通过，然后开会解释安全。编译器还没认他当爹。",
        whyEn: "Current vibe: Saint. First-try compiles, then a safety all-hands. The compiler has not taken his name.",
        srcZh: "Codex / ChatGPT 仍在出货",
        srcEn: "Codex / ChatGPT still shipping",
      },
    ],
  },
  {
    id: "claude",
    zh: "达里奥",
    en: "Dario",
    whoZh: "达里奥 · Claude",
    whoEn: "Dario Amodei · Anthropic",
    meterZh: "宪系强度",
    meterEn: "Claude Intensity",
    hintZh: "← 滑动变祖 · 礼貌越满祖气越浓 →",
    hintEn: "← slide the rheostat · more helpful, more ancestor →",
    current: 1,
    ranks: [
      {
        zh: "小难奥",
        en: "Delayed Dario",
        file: "y-00-nan.webp",
        eventZh: "下一 Fable 还在安全评审里。礼貌先到，模型后到。小难奥。",
        eventEn: "The next Fable sat in safety review. Politeness arrived first. Delayed Dario.",
      },
      {
        zh: "牢奥",
        en: "Jailed Dario",
        file: "y-02-lao.webp",
        eventZh: "疯狂封号，额度说没就没。评论区一边哭一边发 Doge：牢奥。",
        eventEn: "Mass bans. Quotas vanished. The comments posted Doge and called him Jailed Dario.",
      },
      {
        zh: "奥子",
        en: "Dario",
        file: "y-03-zi.webp",
        eventZh: "就是那个很有礼貌的人。宪法写在系统提示里。",
        eventEn: "Just Dario. The constitution lives in the system prompt.",
      },
      {
        zh: "奥圣",
        en: "Saint Dario",
        file: "y-04-saint.webp",
        eventZh: "写代码的人还是先开 Claude。圣在 IDE 里。",
        eventEn: "Coders still open Claude first. Saint of the IDE.",
      },
      {
        zh: "奥神",
        en: "God Dario",
        file: "y-05-god.webp",
        eventZh: "Opus / Fable 封神局。然后被出口管制掐断。",
        eventEn: "Opus/Fable god-tier, then an export control.",
      },
      {
        zh: "奥祖",
        en: "Ancestor Dario",
        file: "y-06-zu.webp",
        eventZh: "宪法祖师。认祖归宗，请你先拒绝。",
        eventEn: "Constitutional ancestor. Please refuse first.",
      },
    ],
    timeline: [
      {
        date: "2021",
        rank: 2,
        whyZh: "从 OpenAI 走出来，把宪法写进系统提示。就是那个很有礼貌的人。",
        whyEn: "Left OpenAI to write a constitution into the system prompt. Just Dario, very polite.",
        srcZh: "Anthropic 创立 / 宪法 AI 论文",
        srcEn: "Anthropic founding / Constitutional AI paper",
      },
      {
        date: "2024-06",
        rank: 3,
        whyZh: "写代码的人还是先开 Claude。圣在 IDE 里，拒绝写在礼貌后面。",
        whyEn: "Coders still opened Claude first. Saint of the IDE, refusal tucked behind please.",
        srcZh: "IDE 插件份额 / 开发者调查",
        srcEn: "IDE plugin share / coder surveys",
      },
      {
        date: "2024-12",
        rank: 0,
        whyZh: "下一 Fable 还在安全评审。礼貌天花板先到，权重后到。小难奥。",
        whyEn: "The next Fable sat in safety review. Polite ceiling first, weights later. Delayed.",
        srcZh: "安全评审口径 / 发布窗口",
        srcEn: "safety-review notes / launch window",
      },
      {
        date: "2025-05",
        rank: 4,
        whyZh: "Opus / Fable 封神局。礼貌天花板，代码一次过。然后管制局开始清嗓子。",
        whyEn: "Opus/Fable god-tier. Polite ceiling, first-try code. Then export control cleared its throat.",
        srcZh: "Fable 发布 / 公开评测",
        srcEn: "Fable launch / public benches",
      },
      {
        date: "2026-06",
        rank: 1,
        whyZh: "美国一纸令下，Fable 5 对外国人关了。全球用户：额度不是没了，是国界。牢奥预告。",
        whyEn: "Washington pulled the plug. Fable 5 vanished for non-US passports. The quota was a border.",
        srcZh: "出口管制通知 / 非美区产品页",
        srcEn: "export-control notice / non-US product page",
      },
      {
        date: "2026-08",
        rank: 1,
        now: true,
        whyZh: "当前风评：牢奥。疯狂封号，额度说没就没。评论区一边哭一边发 Doge。",
        whyEn: "Current vibe: Jailed Dario. Mass bans, vanished quotas. The comments posted Doge and cried.",
        srcZh: "封号潮 / 评论区 Doge 考古",
        srcEn: "ban wave / comment-section Doge archaeology",
      },
    ],
  },
  {
    id: "tibo",
    zh: "Tibo",
    en: "Tibo",
    whoZh: "Tibo · Codex 重置",
    whoEn: "Tibo · Codex Reset",
    meterZh: "重置强度",
    meterEn: "Reset Intensity",
    hintZh: "← 滑动变祖 · 按钮越大祖气越浓 →",
    hintEn: "← slide the rheostat · bigger button, more ancestor →",
    current: 4,
    ranks: [
      {
        zh: "小难Tibo",
        en: "Delayed Tibo",
        file: "y-00-nan.webp",
        eventZh: "额度空了。X 上开始叠「pray for reset」。小难Tibo，还没按。",
        eventEn: "Limits hit zero. X started stacking pray for reset. Delayed Tibo. Button untouched.",
      },
      {
        zh: "牢Tibo",
        en: "Jailed Tibo",
        file: "y-02-lao.webp",
        eventZh: "额度耗干还不按。评论区把他关进牢里：只许按按钮，不许睡觉。",
        eventEn: "Limits dead. Still no press. The comments jailed him: button only, no sleep.",
      },
      {
        zh: "Tibo子",
        en: "Tibo",
        file: "y-03-zi.webp",
        eventZh: "就是那个比利时人。黑帽衫，桌上有个巨大重置按钮。",
        eventEn: "Just Tibo. Black hoodie. Giant reset button on the desk.",
      },
      {
        zh: "Tibo圣",
        en: "Saint Tibo",
        file: "y-04-saint.webp",
        eventZh: "社区建了 Tibo Radar。信徒守夜祈祷。重置圣。",
        eventEn: "They built Tibo Radar. Believers kept vigil. Saint of the extra reset.",
      },
      {
        zh: "Tibo神",
        en: "God Tibo",
        file: "y-05-god.webp",
        eventZh: "一周按好几次。赛博义父，掌管重置的神。",
        eventEn: "Several presses a week. Cyber godfather. God of the reset button.",
      },
      {
        zh: "Tibo祖",
        en: "Ancestor Tibo",
        file: "y-06-zu.webp",
        eventZh: "认祖归宗。从此额度和按钮都以 Tibo 为姓。",
        eventEn: "Ancestor Tibo. Limits and the button take his name.",
      },
    ],
    timeline: [
      {
        date: "2024-07",
        rank: 2,
        whyZh: "从 DeepMind 走进 OpenAI，开始养 Codex。就是那个比利时人，黑帽衫。",
        whyEn: "Left DeepMind for OpenAI and started Codex. Just Tibo, black hoodie.",
        srcZh: "OpenAI / Codex 工程负责人履历",
        srcEn: "OpenAI / Codex eng-lead bio",
      },
      {
        date: "2025-11",
        rank: 3,
        whyZh: "X 上开始按重置。补偿延迟、补偿故障。评论区发明赛博义父。Tibo圣。",
        whyEn: "Started hitting reset on X. Latency gifts, outage gifts. The comments invented cyber godfather.",
        srcZh: "@thsottiaux RESET 帖 / 评论区考古",
        srcEn: "@thsottiaux RESET posts / comment archaeology",
      },
      {
        date: "2026-04",
        rank: 0,
        whyZh: "额度空了，按钮还在休息。X 上叠 pray for reset。小难Tibo。",
        whyEn: "Limits empty. Button napping. X stacked pray for reset. Delayed Tibo.",
        srcZh: "额度仪表盘截图 / 祈祷帖",
        srcEn: "usage-card screenshots / the prayer thread",
      },
      {
        date: "2026-06",
        rank: 1,
        whyZh: "额度耗得太快，开了 warroom。双重置、银行重置，评论区还是喊牢。",
        whyEn: "Limits drained too fast. Warroom. Double reset, banked reset. Comments still said jail.",
        srcZh: "Codex 故障战报 / sneaky double reset",
        srcEn: "Codex incident notes / sneaky double reset",
      },
      {
        date: "2026-07",
        rank: 4,
        whyZh: "GPT-5.6 Sol 把额度烧穿。Tibo 又按了。有人建了 Radar，有人守夜。封神。",
        whyEn: "GPT-5.6 Sol ate the meter. Tibo pressed again. Radar apps. Vigils. God mode.",
        srcZh: "Sol 燃烧率说明 / Tibo Radar",
        srcEn: "Sol burn-rate notes / Tibo Radar",
      },
      {
        date: "2026-08",
        rank: 4,
        now: true,
        whyZh: "当前风评：Tibo神。Hi. It is done. 桌上那个巨大按钮还在响。掌管重置的神。",
        whyEn: "Current vibe: God. Hi. It is done. The giant desk button still clicks. God of resets.",
        srcZh: "@thsottiaux 8 月重置帖 / 社区梗图",
        srcEn: "@thsottiaux August resets / the meme pile",
      },
    ],
  },
  {
    id: "jackie",
    zh: "MakerJackie",
    en: "Jackie",
    whoZh: "MakerJackie · 默默无闻的独立开发者",
    whoEn: "MakerJackie · Nobody indie hacker",
    meterZh: "Jackie强度",
    meterEn: "Jackie Intensity",
    hintZh: "← 滑动变祖 · App 越多祖气越浓 →",
    hintEn: "← slide the rheostat · more apps, more ancestor →",
    current: 0,
    ranks: [
      {
        zh: "小难Jackie",
        en: "Delayed Jackie",
        file: "00-nan.webp",
        eventZh: "做了三十个 App，MRR 还是 0。评论区发明了小难Jackie。",
        eventEn: "Thirty apps. Still $0 MRR. The comments invented Delayed Jackie.",
      },
      {
        zh: "牢Jackie",
        en: "Jailed Jackie",
        file: "02-lao.webp",
        eventZh: "Claude 账单和 Cloudflare 同一周催。房东也在群里@他。评论区喊牢。",
        eventEn: "Claude and Cloudflare billed the same week. The landlord pinged the group chat. Jail.",
      },
      {
        zh: "Jackie子",
        en: "Jackie",
        file: "03-zi.webp",
        eventZh: "就是那个默默无闻的独立开发者。产品还在，收入还在「即将」。",
        eventEn: "Just Jackie. The nobody indie. Product ships. Revenue is still Coming Soon.",
      },
      {
        zh: "Jackie圣",
        en: "Saint Jackie",
        file: "04-saint.webp",
        eventZh: "有个小工具真的有人付费了。月入四位数。圣在独立开发者群里。",
        eventEn: "One tiny tool actually got paid. Four-digit months. Saint of the indie group chat.",
      },
      {
        zh: "Jackie神",
        en: "God Jackie",
        file: "05-god.webp",
        eventZh: "01MVP 出圈。年入七位数，还在说自己是独立开发者。封神。",
        eventEn: "01MVP broke out. Seven-figure year. Still calls himself indie. God.",
      },
      {
        zh: "Jackie祖",
        en: "Ancestor Jackie",
        file: "06-ancestor.webp",
        eventZh: "公司卖掉了。认祖归宗。从此独立开发者以 Jackie 为姓。",
        eventEn: "Sold the company. Ancestor Jackie. Indies take his name.",
      },
    ],
    timeline: [
      {
        date: "2022-03",
        rank: 2,
        whyZh: "辞职做独立开发。第一周上了三个 App。就是那个默默无闻的人。",
        whyEn: "Quit to go indie. Three apps in week one. Just a nobody who ships.",
        srcZh: "Product Hunt 冷场截图 / 个人博客",
        srcEn: "empty Product Hunt / the personal blog",
      },
      {
        date: "2023-06",
        rank: 3,
        whyZh: "有个小工具上了 PH 第三。兴奋了三天。收入 12 美元。短暂的 Jackie圣。",
        whyEn: "A tiny tool hit PH #3. Three days of joy. Twelve dollars. A brief saint.",
        srcZh: "Product Hunt 榜 / Stripe 到账 $12",
        srcEn: "Product Hunt board / Stripe $12",
      },
      {
        date: "2024-11",
        rank: 0,
        whyZh: "累计三十多个 App。总收入还没跑赢 API 账单。评论区发明：小难Jackie。",
        whyEn: "Thirty-plus apps. Lifetime revenue lost to the API bill. The comments coined Delayed Jackie.",
        srcZh: "App 列表考古 / 云账单",
        srcEn: "app-list archaeology / the cloud invoice",
      },
      {
        date: "2025-11",
        rank: 1,
        whyZh: "Claude、Cloudflare、域名续费同一周。房东在群里@他。牢Jackie。",
        whyEn: "Claude, Cloudflare, and the domain, same week. Landlord in the group chat. Jail.",
        srcZh: "催款邮件三联 / 房东消息",
        srcEn: "three dunning emails / the landlord ping",
      },
      {
        date: "2026-08",
        rank: 0,
        now: true,
        whyZh: "收入为 0。还在做第 31 个。当前风评：小难Jackie。祖还在滑杆右边。",
        whyEn: "Income: $0. Shipping app 31. Current vibe: Delayed Jackie. Ancestor is still to the right.",
        srcZh: "Stripe 仪表盘全是零 / 第 31 个仓库",
        srcEn: "Stripe dashboard of zeroes / repo #31",
      },
    ],
  },
];

export function rankSrc(subject, rank) {
  return `/ranks/${subject.id}/${rank.file}`;
}

export function lastIndex(subject = SUBJECTS[0]) {
  return subject.ranks.length - 1;
}
