export const SUBJECTS = [
  {
    id: "musk",
    zh: "马斯克",
    en: "Musk",
    meterZh: "马系强度",
    meterEn: "Musk Intensity",
    hintZh: "← 滑动以增强马系浓度 →",
    hintEn: "← slide to increase musk density →",
    ranks: [
      { zh: "量子马", en: "Quantum", zhSub: "Quantum Musk", enSub: "量子马", file: "01-quantum.webp" },
      { zh: "牢马", en: "Jailed", zhSub: "Jailed Musk", enSub: "牢马", file: "02-lao.webp" },
      { zh: "马子", en: "Elon", zhSub: "Just Elon", enSub: "马子", file: "03-zi.webp" },
      { zh: "马圣", en: "Saint", zhSub: "Saint Musk", enSub: "马圣", file: "04-saint.webp" },
      { zh: "马神", en: "God", zhSub: "God Musk", enSub: "马神", file: "05-god.webp" },
      { zh: "马祖", en: "Ancestor", zhSub: "Ancestor Musk", enSub: "马祖", file: "06-ancestor.webp" },
    ],
  },
  {
    id: "liang",
    zh: "梁文锋",
    en: "Liang",
    meterZh: "梁系强度",
    meterEn: "Liang Intensity",
    hintZh: "← 滑动以增强梁系浓度 →",
    hintEn: "← slide to increase Liang density →",
    ranks: [
      { zh: "量子梁", en: "Quantum", zhSub: "Preview only", enSub: "量子梁", file: "01-quantum.webp" },
      { zh: "牢梁", en: "Jailed", zhSub: "Still delayed", enSub: "牢梁", file: "02-lao.webp" },
      { zh: "梁子", en: "Liang", zhSub: "Just Liang", enSub: "梁子", file: "03-zi.webp" },
      { zh: "梁圣", en: "Saint", zhSub: "Cheap tokens", enSub: "梁圣", file: "04-saint.webp" },
      { zh: "梁神", en: "God", zhSub: "God Liang", enSub: "梁神", file: "05-god.webp" },
      { zh: "梁祖", en: "Ancestor", zhSub: "Ancestor Liang", enSub: "梁祖", file: "06-ancestor.webp" },
    ],
  },
  {
    id: "kimi",
    zh: "Kimi",
    en: "Kimi",
    meterZh: "月系强度",
    meterEn: "Moon Intensity",
    hintZh: "← 滑动以拉长上下文 →",
    hintEn: "← slide to extend the context →",
    ranks: [
      { zh: "量子月", en: "Quantum", zhSub: "Tiny moon", enSub: "量子月", file: "01-quantum.webp" },
      { zh: "牢Kimi", en: "Jailed", zhSub: "Context closed", enSub: "牢Kimi", file: "02-lao.webp" },
      { zh: "Kimi", en: "Kimi", zhSub: "Just Kimi", enSub: "Kimi", file: "03-zi.webp" },
      { zh: "Kimi圣", en: "Saint", zhSub: "Long context", enSub: "Kimi圣", file: "04-saint.webp" },
      { zh: "月神", en: "Moon God", zhSub: "Moonshot", enSub: "月神", file: "05-god.webp" },
      { zh: "Kimi祖", en: "Ancestor", zhSub: "Dark side", enSub: "Kimi祖", file: "06-ancestor.webp" },
    ],
  },
  {
    id: "zhipu",
    zh: "智谱",
    en: "Zhipu",
    meterZh: "谱系强度",
    meterEn: "GLM Intensity",
    hintZh: "← 滑动以增强智谱浓度 →",
    hintEn: "← slide to increase GLM density →",
    ranks: [
      { zh: "量子智", en: "Quantum", zhSub: "Tiny GLM", enSub: "量子智", file: "01-quantum.webp" },
      { zh: "牢谱", en: "Jailed", zhSub: "Paper delayed", enSub: "牢谱", file: "02-lao.webp" },
      { zh: "智子", en: "GLM", zhSub: "Just GLM", enSub: "智子", file: "03-zi.webp" },
      { zh: "智圣", en: "Saint", zhSub: "Open weights", enSub: "智圣", file: "04-saint.webp" },
      { zh: "智神", en: "God", zhSub: "God GLM", enSub: "智神", file: "05-god.webp" },
      { zh: "智祖", en: "Ancestor", zhSub: "Ancestor GLM", enSub: "智祖", file: "06-ancestor.webp" },
    ],
  },
  {
    id: "codex",
    zh: "Codex",
    en: "Codex",
    meterZh: "码系强度",
    meterEn: "Codex Intensity",
    hintZh: "← 滑动以增强代码浓度 →",
    hintEn: "← slide to increase code density →",
    ranks: [
      { zh: "量子码", en: "Quantum", zhSub: "Tiny compiler", enSub: "量子码", file: "01-quantum.webp" },
      { zh: "牢Codex", en: "Jailed", zhSub: "Rate limited", enSub: "牢Codex", file: "02-lao.webp" },
      { zh: "Codex", en: "Codex", zhSub: "Just Codex", enSub: "Codex", file: "03-zi.webp" },
      { zh: "码圣", en: "Saint", zhSub: "It compiles", enSub: "码圣", file: "04-saint.webp" },
      { zh: "码神", en: "God", zhSub: "God of code", enSub: "码神", file: "05-god.webp" },
      { zh: "码祖", en: "Ancestor", zhSub: "Compiler ancestor", enSub: "码祖", file: "06-ancestor.webp" },
    ],
  },
  {
    id: "claude",
    zh: "Claude",
    en: "Claude",
    meterZh: "龙系强度",
    meterEn: "Claude Intensity",
    hintZh: "← 滑动以增强礼貌浓度 →",
    hintEn: "← slide to increase helpfulness →",
    ranks: [
      { zh: "量子龙", en: "Quantum", zhSub: "Tiny dino", enSub: "量子龙", file: "01-quantum.webp" },
      { zh: "牢Claude", en: "Jailed", zhSub: "Usage capped", enSub: "牢Claude", file: "02-lao.webp" },
      { zh: "Claude", en: "Claude", zhSub: "Just Claude", enSub: "Claude", file: "03-zi.webp" },
      { zh: "龙圣", en: "Saint", zhSub: "Very helpful", enSub: "龙圣", file: "04-saint.webp" },
      { zh: "龙神", en: "God", zhSub: "Constitution", enSub: "龙神", file: "05-god.webp" },
      { zh: "龙祖", en: "Ancestor", zhSub: "Ancestor dino", enSub: "龙祖", file: "06-ancestor.webp" },
    ],
  },
];

export function rankSrc(subject, rank) {
  return `/ranks/${subject.id}/${rank.file}`;
}
